language: go

go:
  - tip

install:
  - go get -v github.com/keithballdotnet/arx
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go build github.com/keithballdotnet/arx
  - go test -v -covermode=count -coverprofile=coverage.out github.com/keithballdotnet/arx
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

notifications:
  email: false
